import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'tables/local_meals_table.dart';
import 'tables/local_inventory_table.dart';
import 'tables/local_water_table.dart';
import 'daos/meal_dao.dart';
import 'daos/inventory_dao.dart';
import 'daos/water_dao.dart';

part 'app_database.g.dart'; // generated by build_runner

@DriftDatabase(
  tables: [LocalMeals, LocalInventory, LocalWaterLogs],
  daos: [MealDao, InventoryDao, WaterDao],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (Migrator m) async {
      await m.createAll();
    },
    onUpgrade: (Migrator m, int from, int to) async {
      // Add new migration cases here when schema changes:
      // if (from == 1) { await m.addColumn(table, table.newColumn); }
    },
    beforeOpen: (OpeningDetails details) async {
      await customStatement('PRAGMA foreign_keys = ON');
    },
  );

  static QueryExecutor _openConnection() {
    return driftDatabase(name: 'prodiet_offline');
  }
}
