import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'tables/local_meals_table.dart';
import 'tables/local_inventory_table.dart';
import 'tables/local_water_table.dart';
import 'tables/local_shopping_table.dart';
import 'tables/local_sync_queue_table.dart';
import 'daos/meal_dao.dart';
import 'daos/inventory_dao.dart';
import 'daos/water_dao.dart';
import 'daos/shopping_dao.dart';

part 'app_database.g.dart'; // generated by build_runner


@DriftDatabase(
  tables: [LocalMeals, LocalInventory, LocalWaterLogs, LocalSyncQueue, LocalShoppingList],
  daos: [MealDao, InventoryDao, WaterDao, ShoppingDao],
)

class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 3;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (Migrator m) async {
      await m.createAll();
    },
    onUpgrade: (Migrator m, int from, int to) async {
      if (from < 3) {
        // Migration logic for is_dirty
        await m.alterTable(TableMigration(localMeals, columnTransformer: {
          localMeals.isDirty: localMeals.isDirty, // Mapping from is_synced handled by alterTable if simple
        }));
        await m.alterTable(TableMigration(localInventory));
        await m.alterTable(TableMigration(localWaterLogs));
      }
    },
    beforeOpen: (OpeningDetails details) async {
      await customStatement('PRAGMA foreign_keys = ON');
    },
  );


  static QueryExecutor _openConnection() {
    return driftDatabase(name: 'prodiet_offline');
  }
}
